name: Deploy Direto EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Copiar arquivos via SSH (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/meu-app"

      - name: Executar comandos remotos via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/meu-app
            
            # 1. Atualiza as bibliotecas (libs) baseadas no yarn.lock
            yarn install --frozen-lockfile
            
            # 2. Roda o build para gerar a pasta /dist
            yarn build
            
            # 3. Reinicia o processo no PM2
            # Usamos o caminho dist/main.js que é o padrão do NestJS
            pm2 restart boilerplate || pm2 start dist/main.js --name boilerplate
            
            # 4. Salva a lista de processos para persistir após reboot da EC2
            pm2 save

